In [1]:
# 📦 Importar bibliotecas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

# 📥 Carregar dados
url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
df = pd.read_csv(url)

# 👀 Ver dados
print(df.head())
print(df['Class'].value_counts())

# 🎯 Separar features e target
X = df.drop('Class', axis=1)
y = df['Class']

# ✂️ Dividir treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 🤖 Treinar modelo (Regressão Linear)
model = LinearRegression()
model.fit(X_train, y_train)

# 🔮 Fazer previsões
y_pred = model.predict(X_test)

# 🔄 Converter previsões para 0 ou 1 (threshold 0.5)
y_pred_class = (y_pred > 0.5).astype(int)

# 📊 Avaliar acurácia
accuracy = accuracy_score(y_test, y_pred_class)
print(f"Acurácia: {accuracy:.4f}")

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28 

O primeiro teste foi utilizando a Regressão Linear. Agora vamos utilizar Regressão Logística

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Modelo melhor
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Previsões
y_pred = model.predict(X_test)

# Avaliação completa
print("Acurácia:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório:")
print(classification_report(y_test, y_pred))

Acurácia: 0.9989466661985184

Matriz de confusão:
[[56854    10]
 [   50    48]]

Relatório:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.83      0.49      0.62        98

    accuracy                           1.00     56962
   macro avg       0.91      0.74      0.81     56962
weighted avg       1.00      1.00      1.00     56962



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
A seguir vamos ver como fazer Balanceamento (SMOTE)

In [4]:
# ⚖️ Aplicar SMOTE SOMENTE no treino
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Antes do SMOTE:")
print(y_train.value_counts())

print("\nDepois do SMOTE:")
print(pd.Series(y_train_res).value_counts())

# 🤖 Treinar modelo
model = LogisticRegression(max_iter=1000)
model.fit(X_train_res, y_train_res)

# 🔮 Previsões
y_pred = model.predict(X_test)

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))

print("\nMatriz de confusão:")

Antes do SMOTE:
Class
0    227451
1       394
Name: count, dtype: int64

Depois do SMOTE:
Class
0    227451
1    227451
Name: count, dtype: int64

Acurácia: 0.9892208840981707

Matriz de confusão:


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Agora vamos usar RandomForest. Os parâmetros foram reduzidos devido ao tamanho do dataset

In [8]:
from sklearn.ensemble import RandomForestClassifier
# 🌲 Modelo Random Forest
model = RandomForestClassifier(
    n_estimators=30,
    max_depth=8,
    max_features='sqrt',
    n_jobs=-1,
    random_state=42
)

# 🤖 Treinar
model.fit(X_train, y_train)

# 🔮 Previsões
y_pred = model.predict(X_test)

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))

print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de classificação:")
print(classification_report(y_test, y_pred))


Acurácia: 0.9995084442259752

Matriz de confusão:
[[56861     3]
 [   25    73]]

Relatório de classificação:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.96      0.74      0.84        98

    accuracy                           1.00     56962
   macro avg       0.98      0.87      0.92     56962
weighted avg       1.00      1.00      1.00     56962



Agora vamos ver como usar XGBoost com base nos dados originais

In [6]:
!pip install xgboost
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from xgboost import XGBClassifier

# ⚖️ Calcular peso da classe (IMPORTANTÍSSIMO)
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# 🚀 Modelo XGBoost
model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,  # 🔥 chave para dados desbalanceados
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

# 🤖 Treinar
model.fit(X_train, y_train)

# 🔮 Previsões
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# 📊 Avaliação
print("\nAcurácia:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nMatriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("\nRelatório de classificação:")
print(classification_report(y_test, y_pred))

scale_pos_weight: 577.29

Acurácia: 0.9996137776061234
ROC-AUC: 0.9892902363534046

Matriz de confusão:
[[56858     6]
 [   16    82]]

Relatório de classificação:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.93      0.84      0.88        98

    accuracy                           1.00     56962
   macro avg       0.97      0.92      0.94     56962
weighted avg       1.00      1.00      1.00     56962

